[colors.bright]
black = "0x4d4d4d"
blue = "0xcaa9fa"
cyan = "0xaa91e3"
green = "0x5af78e"
magenta = "0xff92d0"
red = "0xff6e67"
white = "0xe6e6e6"
yellow = "0xeaf08d"

[colors.cursor]
cursor = "0xf8f8f2"
text = "0x191622"

[colors.dim]
black = "0x000000"
blue = "0x530aba"
cyan = "0x433364"
green = "0x049f2b"
magenta = "0xbb006b"
red = "0xa90000"
white = "0x5f5f5f"
yellow = "0xa3b106"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8d79ba"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xeffa78"

[colors.primary]
background = "0x191622"
foreground = "0xe1e1e6"

[cursor]
thickness = 0.15
unfocused_hollow = false

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 16

[font.bold]
family = "Ubuntu Mono"

[font.italic]
family = "Ubuntu Mono"

[font.normal]
family = "Ubuntu Mono"

[window]
opacity = 0.7

[window.padding]
x = 10
y = 10
